name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request: {}
  workflow_dispatch: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Run Tests
        run: yarn test

  E2E:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - uses: actions/cache@v3
        id: cache-cypress
        with:
          path: '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-cypress-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Run Tests
        run: yarn e2e

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: ESLint
        run: yarn lint

  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Prettier
        run: yarn format:check

  Build-Apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build apps
        run: yarn build

  Build-Storybooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build storybooks
        run: yarn build-storybook
